"""initial

Revision ID: 35e9f6eea385
Revises: 
Create Date: 2026-06-02 20:46:47.593508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '35e9f6eea385'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_config')
    op.drop_table('behavior_logs')
    op.drop_table('agent_files')
    op.drop_table('needs')
    op.drop_table('matches')
    op.drop_table('agent_messages')
    op.drop_table('agent_tasks')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_need_applications_applicant_user_id'), table_name='need_applications')
    op.drop_index(op.f('ix_need_applications_need_id'), table_name='need_applications')
    op.drop_table('need_applications')
    op.drop_table('messages')
    op.drop_table('agent_sessions')
    op.drop_table('match_memory')
    op.drop_index(op.f('ix_skill_graph_skill_a'), table_name='skill_graph')
    op.drop_index(op.f('ix_skill_graph_skill_b'), table_name='skill_graph')
    op.drop_table('skill_graph')
    op.drop_table('preference_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference_profiles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('preference_vector', sqlite.JSON(), nullable=True),
    sa.Column('behavioral_tags', sqlite.JSON(), nullable=True),
    sa.Column('last_reflected_at', sa.DATETIME(), nullable=True),
    sa.Column('reflection_count', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('skill_graph',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('skill_a', sa.VARCHAR(length=100), nullable=False),
    sa.Column('skill_b', sa.VARCHAR(length=100), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_a', 'skill_b')
    )
    op.create_index(op.f('ix_skill_graph_skill_b'), 'skill_graph', ['skill_b'], unique=False)
    op.create_index(op.f('ix_skill_graph_skill_a'), 'skill_graph', ['skill_a'], unique=False)
    op.create_table('match_memory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('need_description', sa.TEXT(), nullable=False),
    sa.Column('need_embedding', sqlite.JSON(), nullable=False),
    sa.Column('matched_user_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('ai_reason', sa.TEXT(), nullable=False),
    sa.Column('feedback', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_sessions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('summary', sa.TEXT(), nullable=True),
    sa.Column('planning_state', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('need_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['need_id'], ['needs.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('need_applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('need_id', sa.INTEGER(), nullable=False),
    sa.Column('applicant_user_id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('owner_reply', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['need_id'], ['needs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_need_applications_need_id'), 'need_applications', ['need_id'], unique=False)
    op.create_index(op.f('ix_need_applications_applicant_user_id'), 'need_applications', ['applicant_user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('skill_tags', sqlite.JSON(), nullable=True),
    sa.Column('profile_embedding', sqlite.JSON(), nullable=True),
    sa.Column('avatar', sa.TEXT(), nullable=True),
    sa.Column('school', sa.VARCHAR(length=100), nullable=True),
    sa.Column('extra', sqlite.JSON(), nullable=True),
    sa.Column('rating_score', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_table('agent_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_task_id', sa.INTEGER(), nullable=True),
    sa.Column('goal', sa.VARCHAR(length=300), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('assigned_agent', sa.VARCHAR(length=50), nullable=True),
    sa.Column('result', sqlite.JSON(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('input_data', sqlite.JSON(), nullable=True),
    sa.Column('error_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('retry_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('need_id', sa.INTEGER(), nullable=True),
    sa.Column('match_id', sa.INTEGER(), nullable=True),
    sa.Column('file_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['parent_task_id'], ['agent_tasks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('token_count', sa.INTEGER(), nullable=True),
    sa.Column('extra_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('need_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('ai_reason', sa.TEXT(), nullable=False),
    sa.Column('feedback', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['need_id'], ['needs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('needs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('req_tags', sqlite.JSON(), nullable=True),
    sa.Column('need_embedding', sqlite.JSON(), nullable=True),
    sa.Column('selection_mode', sa.VARCHAR(length=20), nullable=True),
    sa.Column('selected_user_ids', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=200), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('content_text', sa.TEXT(), nullable=False),
    sa.Column('extracted_info', sqlite.JSON(), nullable=True),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('behavior_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('target_user_id', sa.INTEGER(), nullable=True),
    sa.Column('need_id', sa.INTEGER(), nullable=True),
    sa.Column('extra_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['need_id'], ['needs.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_config',
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.VARCHAR(length=500), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###
